In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(
    r"C:\Users\USER\Desktop\Data_Analytics_Project\1. Weather Data.csv"
)

Q.1) Find the shape of the dataset.

In [3]:
data.shape

(8784, 8)

Q.2) Display all column names.

In [4]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='str')

Q.3) Get complete information about the dataset.

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   str
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   str
dtypes: float64(4), int64(2), str(2)
memory usage: 549.1 KB

Q.4) Find all unique weather conditions.

In [6]:
data['Weather'].unique()

<StringArray>
[                                    'Fog',
                    'Freezing Drizzle,Fog',
                           'Mostly Cloudy',
                                  'Cloudy',
                                    'Rain',
                            'Rain Showers',
                            'Mainly Clear',
                            'Snow Showers',
                                    'Snow',
                                   'Clear',
                       'Freezing Rain,Fog',
                           'Freezing Rain',
                        'Freezing Drizzle',
                               'Rain,Snow',
                           'Moderate Snow',
                   'Freezing Drizzle,Snow',
               'Freezing Rain,Snow Grains',
                       'Snow,Blowing Snow',
                            'Freezing Fog',
                                    'Haze',
                                'Rain,Fog',
                             'Drizzle,Fog',
                                 'Drizzle',
                   'Freezing Drizzle,Haze',
                      'Freezing Rain,Haze',
                               'Snow,Haze',
                                'Snow,Fog',
                        'Snow,Ice Pellets',
                               'Rain,Haze',
                      'Thunderstorms,Rain',
              'Thunderstorms,Rain Showers',
        'Thunderstorms,Heavy Rain Showers',
          'Thunderstorms,Rain Showers,Fog',
                           'Thunderstorms',
                  'Thunderstorms,Rain,Fog',
 'Thunderstorms,Moderate Rain Showers,Fog',
                        'Rain Showers,Fog',
               'Rain Showers,Snow Showers',
                            'Snow Pellets',
                           'Rain,Snow,Fog',
                       'Moderate Rain,Fog',
           'Freezing Rain,Ice Pellets,Fog',
                 'Drizzle,Ice Pellets,Fog',
                            'Drizzle,Snow',
                        'Rain,Ice Pellets',
                        'Drizzle,Snow,Fog',
                        'Rain,Snow Grains',
                   'Rain,Snow,Ice Pellets',
                        'Snow Showers,Fog',
              'Moderate Snow,Blowing Snow']
Length: 50, dtype: str

Q.5) Count the number of unique weather conditions.

In [7]:
data['Weather'].nunique()

50

Q.6) Find how many times each weather condition occurred.

In [9]:
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Freezing Fog                                  4
Rain,Snow,Ice Pellets                         4
Snow Showers,Fog                              4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Rain,Fog                        1
Thunderstorms,Moderate Rain Showers,Fog       1
Rain Showers,Fog                              1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

Q.7) Find all records where Weather is Clear.

In [10]:
data[data['Weather'] == 'Clear']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

Q.8) Find how many times each weather condition occurred.

In [15]:
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Freezing Fog                                  4
Rain,Snow,Ice Pellets                         4
Snow Showers,Fog                              4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Rain,Fog                        1
Thunderstorms,Moderate Rain Showers,Fog       1
Rain Showers,Fog                              1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

Q.9) Find all records where Temperature > 0 and Humidity > 50.

In [18]:
data[(data['Temp_C'] > 0) & (data['Rel Hum_%'] > 50)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
13,1/1/2012 13:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,1/1/2012 14:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,1/1/2012 15:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,1/1/2012 16:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,1/1/2012 17:00,3.0,0.0,81,13,16.1,99.81,Cloudy
...,...,...,...,...,...,...,...,...
8546,12/22/2012 2:00,1.1,0.1,93,30,8.0,97.89,"Drizzle,Snow,Fog"
8547,12/22/2012 3:00,1.1,0.1,93,28,9.7,97.93,"Drizzle,Snow,Fog"
8548,12/22/2012 4:00,0.6,-0.6,92,35,11.3,97.98,Snow
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow

Q.10) Find all records where weather contains 'Snow'.

In [19]:
data[data['Weather'].str.contains('Snow')]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
41,1/2/2012 17:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,1/2/2012 20:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,1/2/2012 21:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,1/2/2012 23:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,1/3/2012 0:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

Q.11) Group data by Weather and find average temperature.

In [20]:
data.groupby('Weather')['Temp_C'].mean()

Weather
Clear                                       6.825716
Cloudy                                      7.970544
Drizzle                                     7.353659
Drizzle,Fog                                 8.067500
Drizzle,Ice Pellets,Fog                     0.400000
Drizzle,Snow                                1.050000
Drizzle,Snow,Fog                            0.693333
Fog                                         4.303333
Freezing Drizzle                           -5.657143
Freezing Drizzle,Fog                       -2.533333
Freezing Drizzle,Haze                      -5.433333
Freezing Drizzle,Snow                      -5.109091
Freezing Fog                               -7.575000
Freezing Rain                              -3.885714
Freezing Rain,Fog                          -2.225000
Freezing Rain,Haze                         -4.900000
Freezing Rain,Ice Pellets,Fog              -2.600000
Freezing Rain,Snow Grains                  -5.000000
Haze                                       -0.200000
Mainly Clear                               12.558927
Moderate Rain,Fog                           1.700000
Moderate Snow                              -5.525000
Moderate Snow,Blowing Snow                 -5.450000
Mostly Cloudy                              10.574287
Rain                                        9.786275
Rain Showers                               13.722340
Rain Showers,Fog                           12.800000
Rain Showers,Snow Showers                   2.150000
Rain,Fog                                    8.273276
Rain,Haze                                   4.633333
Rain,Ice Pellets                            0.600000
Rain,Snow                                   1.055556
Rain,Snow Grains                            1.900000
Rain,Snow,Fog                               0.800000
Rain,Snow,Ice Pellets                       1.100000
Snow                                       -4.524103
Snow Pellets                                0.700000
Snow Showers                               -3.506667
Snow Showers,Fog                          -10.675000
Snow,Blowing Snow                          -5.410526
Snow,Fog                                   -5.075676
Snow,Haze                                  -4.020000
Snow,Ice Pellets                           -1.883333
Thunderstorms                              24.150000
Thunderstorms,Heavy Rain Showers           10.900000
Thunderstorms,Moderate Rain Showers,Fog    19.600000
Thunderstorms,Rain                         20.433333
Thunderstorms,Rain Showers                 20.037500
Thunderstorms,Rain Showers,Fog             21.600000
Thunderstorms,Rain,Fog                     20.600000
Name: Temp_C, dtype: float64

Q.12) Find all null values in the dataset.

In [21]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64